# Eris Theme Configuration

# Theme settings
title: Eris Theme
description: A modern, minimalist Jekyll theme with a distinctive purple color scheme
url: ""
baseurl: ""

# Navigation
navigation:
  - title: Blog
    url: /blog.html
  - title: Projects
    url: /projects.html
    submenu:
      - title: Project 1
        url: /projects/project1.html
      - title: Project 2
        url: /projects/project2.html
  - title: About
    url: /about.html
  - title: Contact
    url: /contact.html

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Process HTML files
include:
  - _includes
  - assets
  - "*.html"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md
  - eris-theme.gemspec
  - LICENSE.txt

# Theme color settings
theme_color:
  primary: "#6d105a"
  text: "#ffffff"

# Author information
author:
  name: Your Name
  email: your.email@example.com
  twitter: yourtwitter
  github: yourgithub

# Social media links
social:
  bluesky: https://bsky.app/profile/yourusername
  linkedin: https://www.linkedin.com/in/yourusername
  instagram: https://www.instagram.com/yourusername
  github: https://github.com/yourusername
