source "https://rubygems.org"

# Specify your gem's dependencies in eris-theme.gemspec
gemspec

# Jekyll and plugins
gem "jekyll", "~> 4.2"
gem "jekyll-feed", "~> 0.16"
gem "jekyll-seo-tag", "~> 2.8"

# Development dependencies
group :development do
  gem "bundler", "~> 2.3"
  gem "rake", "~> 13.0"
end
